services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - 8081:8080
    networks:
      - relatos-de-papel-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb

networks:
  relatos-de-papel-network:
    driver: bridge